### ISSUE TITLE
为什么要在update里再次执行一遍oldBinding.value

### ISSUE THREAD

**Issue by fxxjdedd** [vueComponent/vue-ref#1]
https://github.com/vueComponent/vue-ref/blob/20076f2ebc083f9b86f08770aa6b50488bd47692/index.js#L21

我觉的这一是个很常见的使用场景，这种写法在每次update时，v-ref的回调函数会是一个全新的函数，然后compRef就会再次设置为null
```
<Dialog v-ref="comp => this.compRef = comp"></Dialog>
```

**Comment by tangjinzhou** [comment]
1. 为了释放内存
场景：`<Dialog v-ref="this.refA"></Dialog>` 更改成 `<Dialog v-ref="this.refB"></Dialog>`
这时要把 refA中的值给设置null  
2. this.compRef 不应该是响应式数据，也不能是响应式数据，也没必要是响应式数据
设置null没什么问题

**Comment by fxxjdedd** [comment]
多谢回复，我理解您的意思了。
